import React from "react";
import { Activity, BarChart3, CalendarDays, CircleDollarSign, Compass, Layers3, Target, TrendingUp } from "lucide-react";
import { trpc } from "@/lib/trpc";

type PerformanceRow = { key: string; tradeCount: number; wins: number; losses: number; winRate: number; pnl: number; averagePnl: number; profitFactor: number | null };

function number(value: number) {
  return new Intl.NumberFormat("en-US", { maximumFractionDigits: 2, minimumFractionDigits: 2 }).format(value);
}

function Pnl({ value }: { value: number }) {
  return <span className={value >= 0 ? "text-emerald-300" : "text-rose-300"}>{value >= 0 ? "+" : "-"}${number(Math.abs(value))}</span>;
}

function Metric({ label, value, detail, icon: Icon, signal = "blue" }: { label: string; value: React.ReactNode; detail: string; icon: typeof Target; signal?: "green" | "blue" | "amber" }) {
  const iconTone = signal === "green" ? "text-emerald-300 bg-emerald-400/[0.10]" : signal === "amber" ? "text-amber-200 bg-amber-300/[0.10]" : "text-sky-300 bg-sky-400/[0.10]";
  return <article className="tf-kpi-card rounded-2xl p-4"><div className="flex items-center justify-between"><span className="font-mono text-[9px] uppercase tracking-[0.18em] text-slate-500">{label}</span><span className={`grid h-7 w-7 place-items-center rounded-lg ${iconTone}`}><Icon className="h-3.5 w-3.5" /></span></div><div className="mt-4 text-2xl font-semibold tracking-[-0.05em] text-white">{value}</div><p className="mt-1 text-xs text-slate-500">{detail}</p></article>;
}

function Breakdown({ title, rows, empty, icon: Icon }: { title: string; rows: PerformanceRow[]; empty: string; icon: typeof Layers3 }) {
  const maxMagnitude = Math.max(1, ...rows.map(row => Math.abs(row.pnl)));
  return <section className="tf-workspace-surface rounded-2xl p-5"><div className="mb-4 flex items-center justify-between"><div className="flex items-center gap-2"><span className="grid h-7 w-7 place-items-center rounded-lg bg-white/[0.05] text-emerald-300"><Icon className="h-3.5 w-3.5" /></span><h2 className="text-sm font-semibold text-white">{title}</h2></div><span className="font-mono text-[9px] uppercase tracking-[0.15em] text-slate-600">Live only</span></div>{rows.length === 0 ? <div className="rounded-xl border border-dashed border-white/[0.12] bg-[#07101f]/35 px-4 py-7 text-center"><p className="text-sm text-slate-400">{empty}</p><p className="mt-1 text-[11px] text-slate-600">Your private journal data will appear here automatically.</p></div> : <div className="space-y-2.5">{rows.slice(0, 6).map(row => <div key={row.key} className="rounded-xl border border-white/[0.07] bg-[#07101f]/55 p-3 transition-colors hover:border-emerald-300/[0.18] hover:bg-emerald-400/[0.035]"><div className="flex items-center justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-medium text-slate-100">{row.key}</p><p className="mt-0.5 text-[11px] text-slate-500">{row.tradeCount} trades · {number(row.winRate)}% win rate · PF {row.profitFactor === null ? "—" : number(row.profitFactor)}</p></div><p className="font-mono text-sm font-semibold"><Pnl value={row.pnl} /></p></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-slate-800"><div className={row.pnl >= 0 ? "h-full rounded-full bg-gradient-to-r from-emerald-500 to-emerald-300" : "h-full rounded-full bg-gradient-to-r from-rose-600 to-rose-400"} style={{ width: `${Math.max(5, (Math.abs(row.pnl) / maxMagnitude) * 100)}%` }} /></div></div>)}</div>}</section>;
}

export default function Analytics() {
  const { data, isLoading, error, refetch, isFetching } = trpc.analytics.overview.useQuery();
  if (isLoading) return <div className="min-h-[60vh] bg-[#07101f] px-5 py-8 lg:px-8"><div className="mx-auto max-w-[1640px] animate-pulse"><div className="h-4 w-36 rounded bg-white/[0.06]" /><div className="mt-3 h-10 w-72 rounded bg-white/[0.06]" /><div className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[0, 1, 2, 3].map(item => <div key={item} className="h-32 rounded-2xl border border-white/[0.06] bg-white/[0.035]" />)}</div></div></div>;
  if (error || !data) return <div className="grid min-h-[60vh] place-items-center bg-[#07101f] px-6 text-center"><div className="tf-workspace-surface max-w-sm rounded-2xl p-7"><p className="text-sm text-rose-300">Analytics could not load.</p><p className="mt-2 text-xs leading-5 text-slate-500">Your journal data remains private. Retry when your secure sync connection is available.</p><button onClick={() => refetch()} className="tf-press mt-4 rounded-lg border border-emerald-300/[0.22] bg-emerald-400/[0.08] px-3 py-2 text-xs text-emerald-100">{isFetching ? "Retrying…" : "Retry analytics"}</button></div></div>;
  const { summary } = data;
  const leadSetup = data.setups[0];
  const bestSymbol = data.symbols[0];
  return <div className="min-h-full bg-[#07101f] text-slate-100"><main className="mx-auto w-full max-w-[1640px] px-5 py-7 lg:px-8 lg:py-9"><section className="mb-6 flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><div><p className="font-mono text-[10px] uppercase tracking-[0.22em] text-emerald-300">Private performance intelligence</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.04em] text-white sm:text-4xl">Setup Analytics</h1><p className="mt-2 max-w-2xl text-sm text-slate-500">Read your live execution patterns with the same discipline you apply to a chart. Backtest simulations remain excluded.</p></div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full border border-emerald-300/[0.16] bg-emerald-400/[0.08] px-3 py-2 font-mono text-[9px] uppercase tracking-[0.14em] text-emerald-200">Live journal only</span><span className="rounded-full border border-white/[0.09] bg-white/[0.03] px-3 py-2 font-mono text-[9px] uppercase tracking-[0.14em] text-slate-500">Recorded P&amp;L basis</span></div></section>
    <section className="tf-workspace-surface mb-5 grid gap-3 rounded-2xl p-3 md:grid-cols-2"><div className="rounded-xl border border-emerald-300/[0.12] bg-gradient-to-br from-emerald-400/[0.10] to-transparent p-4"><div className="flex items-center gap-2 font-mono text-[9px] uppercase tracking-[0.18em] text-emerald-300"><Activity className="h-3.5 w-3.5" /> Strongest current setup</div><p className="mt-3 text-lg font-semibold text-white">{leadSetup ? leadSetup.key : "Add a tagged execution"}</p><p className="mt-1 text-xs text-slate-400">{leadSetup ? <><Pnl value={leadSetup.pnl} /> · {leadSetup.tradeCount} logged trades · {number(leadSetup.winRate)}% win rate</> : "Start with a saved setup in your manual journal form."}</p></div><div className="rounded-xl border border-sky-300/[0.12] bg-gradient-to-br from-sky-400/[0.08] to-transparent p-4"><div className="flex items-center gap-2 font-mono text-[9px] uppercase tracking-[0.18em] text-sky-300"><Compass className="h-3.5 w-3.5" /> Highest-volume symbol</div><p className="mt-3 text-lg font-semibold text-white">{bestSymbol ? bestSymbol.key : "No symbols logged"}</p><p className="mt-1 text-xs text-slate-400">{bestSymbol ? <>{bestSymbol.tradeCount} live executions · <Pnl value={bestSymbol.pnl} /></> : "Log a live trade to establish your symbol breakdown."}</p></div></section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Recorded P&L" value={<Pnl value={summary.pnl} />} detail={`${summary.tradeCount} live executions`} icon={CircleDollarSign} signal="green" /><Metric label="Win rate" value={`${number(summary.winRate)}%`} detail={`${summary.wins} wins · ${summary.losses} losses`} icon={Target} signal="green" /><Metric label="Profit factor" value={summary.profitFactor === null ? "—" : number(summary.profitFactor)} detail="Gross wins ÷ gross losses" icon={TrendingUp} /><Metric label="Average P&L" value={<Pnl value={summary.averagePnl} />} detail="Recorded P&L per trade" icon={Compass} signal="amber" /></section>
    <section className="mt-5 grid gap-5 xl:grid-cols-2"><Breakdown title="Performance by setup" rows={data.setups} empty="Add a saved setup when logging trades to compare your playbooks." icon={Layers3} /><Breakdown title="Performance by symbol" rows={data.symbols} empty="Log a live trade to start your symbol breakdown." icon={BarChart3} /><Breakdown title="Long vs short" rows={data.directions} empty="Direction patterns will appear after you log trades." icon={TrendingUp} /><Breakdown title="Performance by market session" rows={data.sessions} empty="Choose a market session when logging trades to compare timing patterns." icon={CalendarDays} /><Breakdown title="Performance by weekday" rows={data.weekdays} empty="Trading-day patterns will appear after you log trades." icon={Activity} /></section>
    <div className="mt-5 rounded-2xl border border-white/[0.08] bg-white/[0.025] p-4 text-xs leading-5 text-slate-500"><BarChart3 className="mr-2 inline h-4 w-4 text-emerald-300" />Setup Analytics uses the P&amp;L recorded in your private live journal. It does not use, publish, or combine any simulated Backtest results.</div></main></div>;
}
