import React, { useMemo } from "react";
import { Activity, ArrowRight, BarChart3, BookOpenCheck, CalendarDays, ChartNoAxesCombined, FlaskConical, Gauge, Plus, ShieldCheck, Target, TrendingUp } from "lucide-react";
import { useLocation } from "wouter";
import { trpc } from "@/lib/trpc";
import { appRoutes } from "@/lib/appRoutes";

function money(value: number) {
  return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 2 }).format(value);
}

function equityPath(trades: { date: string; pnl: number }[]) {
  const series = [...trades].sort((a, b) => a.date.localeCompare(b.date));
  if (!series.length) return "";
  let balance = 0;
  const values = series.map(trade => (balance += trade.pnl));
  const min = Math.min(0, ...values);
  const max = Math.max(0, ...values);
  const range = Math.max(max - min, 1);
  return values.map((value, index) => {
    const x = values.length === 1 ? 300 : 18 + (index / (values.length - 1)) * 564;
    const y = 178 - ((value - min) / range) * 142;
    return `${index ? "L" : "M"} ${x.toFixed(1)} ${y.toFixed(1)}`;
  }).join(" ");
}

function Metric({ label, value, detail, tone, icon: Icon }: { label: string; value: string; detail: string; tone: "blue" | "emerald" | "violet" | "amber"; icon: React.ElementType }) {
  const tones = { blue: "text-blue-300 bg-blue-500/[.055] border-blue-400/15", emerald: "text-emerald-300 bg-emerald-500/[.055] border-emerald-400/15", violet: "text-violet-300 bg-violet-500/[.055] border-violet-400/15", amber: "text-amber-200 bg-amber-500/[.055] border-amber-400/15" }[tone];
  return <section className="relative overflow-hidden rounded-2xl border border-white/[.07] bg-[#0a111f] p-4 shadow-[0_16px_32px_rgba(0,0,0,.18)]"><div className={`absolute right-4 top-4 grid h-8 w-8 place-items-center rounded-lg border ${tones}`}><Icon className="h-4 w-4" /></div><p className="font-mono text-[9px] uppercase tracking-[.18em] text-slate-500">{label}</p><p className="mt-3 pr-9 font-mono text-2xl font-semibold tracking-[-.05em] text-white">{value}</p><p className="mt-1.5 text-[11px] text-slate-500">{detail}</p><div className="absolute bottom-0 left-5 right-5 h-px bg-gradient-to-r from-transparent via-white/[.12] to-transparent" /></section>;
}

export default function Home() {
  const [, setLocation] = useLocation();
  const { data: trades = [] } = trpc.trades.list.useQuery();
  const overview = useMemo(() => {
    const totalPnl = trades.reduce((sum, trade) => sum + trade.pnl, 0);
    const wins = trades.filter(trade => trade.pnl > 0);
    const losses = trades.filter(trade => trade.pnl < 0);
    const now = new Date();
    const monthKey = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`;
    const monthPnl = trades.filter(trade => trade.date.startsWith(monthKey)).reduce((sum, trade) => sum + trade.pnl, 0);
    const winRate = trades.length ? (wins.length / trades.length) * 100 : 0;
    const averageWin = wins.length ? wins.reduce((sum, trade) => sum + trade.pnl, 0) / wins.length : 0;
    const averageLoss = losses.length ? losses.reduce((sum, trade) => sum + trade.pnl, 0) / losses.length : 0;
    const factor = averageLoss < 0 ? Math.abs(averageWin / averageLoss) : averageWin > 0 ? Infinity : 0;
    return { totalPnl, wins, losses, monthPnl, winRate, averageWin, averageLoss, factor, recent: [...trades].sort((a, b) => b.date.localeCompare(a.date)).slice(0, 4) };
  }, [trades]);
  const path = useMemo(() => equityPath(trades), [trades]);
  const logTrade = () => { setLocation(appRoutes.trades); window.setTimeout(() => window.dispatchEvent(new Event("trade-fusion:open-log-trade")), 120); };

  return <div className="min-h-full bg-[#06090f] text-foreground"><main className="mx-auto w-full max-w-[1720px] px-4 py-5 sm:px-5 lg:px-7 lg:py-6">
    <section className="mb-5 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="font-mono text-[9px] uppercase tracking-[.22em] text-blue-300">Live-trade command center</p><h1 className="mt-1.5 text-2xl font-semibold tracking-[-.04em] text-white sm:text-3xl">Dashboard</h1><p className="mt-1.5 text-xs text-slate-500">Private journal performance · Backtest excluded</p></div><div className="flex flex-wrap gap-2"><button type="button" onClick={() => setLocation(appRoutes.journal)} className="tf-press inline-flex items-center gap-1.5 rounded-xl border border-white/[.08] bg-white/[.025] px-3 py-2 text-xs text-slate-300 hover:bg-white/[.06]"><BookOpenCheck className="h-3.5 w-3.5 text-blue-300" />Open Journal</button><button type="button" onClick={logTrade} className="tf-press inline-flex items-center gap-1.5 rounded-xl bg-gradient-to-br from-blue-400 to-blue-500 px-3 py-2 text-xs font-semibold text-white shadow-[0_10px_24px_oklch(.38_.16_250_/.28)]"><Plus className="h-4 w-4" />Log Trade</button></div></section>
    <section className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Recorded P&L" value={money(overview.totalPnl)} detail={`${trades.length} closed live trade${trades.length === 1 ? "" : "s"}`} tone="blue" icon={ChartNoAxesCombined} /><Metric label="This month" value={money(overview.monthPnl)} detail={new Date().toLocaleString("en-US", { month: "long", year: "numeric" })} tone={overview.monthPnl >= 0 ? "emerald" : "amber"} icon={TrendingUp} /><Metric label="Win rate" value={`${overview.winRate.toFixed(1)}%`} detail={`${overview.wins.length} wins · ${overview.losses.length} losses`} tone="violet" icon={Target} /><Metric label="Journal reviews" value={trades.length ? `${trades.length}` : "0"} detail="Add an idea or review to each trade." tone="amber" icon={BookOpenCheck} /></section>
    <section className="grid gap-4 2xl:grid-cols-[minmax(0,1.45fr)_minmax(340px,.85fr)]"><section className="overflow-hidden rounded-2xl border border-white/[.07] bg-[#0a111f] p-4 shadow-[0_18px_38px_rgba(0,0,0,.2)] sm:p-5"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-[9px] uppercase tracking-[.18em] text-slate-500">Recorded performance</p><p className={`mt-2 font-mono text-3xl font-semibold tracking-[-.06em] ${overview.totalPnl > 0 ? "text-emerald-300" : overview.totalPnl < 0 ? "text-rose-300" : "text-white"}`}>{money(overview.totalPnl)}</p></div><span className="rounded-md border border-blue-400/15 bg-blue-500/[.06] px-2 py-1 font-mono text-[9px] text-blue-200">LIVE JOURNAL</span></div><div className="relative mt-5 h-52 overflow-hidden rounded-xl border border-white/[.06] bg-[#070d18] sm:h-60"><div className="pointer-events-none absolute inset-0 opacity-40 [background-image:linear-gradient(#31415b_1px,transparent_1px),linear-gradient(90deg,#31415b_1px,transparent_1px)] [background-size:72px_48px]" />{path ? <svg viewBox="0 0 600 200" preserveAspectRatio="none" className="absolute inset-0 h-full w-full" aria-label="Recorded live-trade P and L trend"><path d={path} fill="none" stroke={overview.totalPnl >= 0 ? "#34d399" : "#fb7185"} strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" /></svg> : <div className="relative grid h-full place-items-center text-center"><div><Gauge className="mx-auto h-6 w-6 text-slate-700" /><p className="mt-3 text-sm text-slate-500">Log your first live trade to begin the curve.</p><button type="button" onClick={logTrade} className="mt-3 font-mono text-[10px] uppercase tracking-[.16em] text-blue-300">Log trade <ArrowRight className="inline h-3.5 w-3.5" /></button></div></div>}<div className="absolute bottom-3 left-3 rounded-md border border-white/[.08] bg-[#070d18]/90 px-2 py-1 font-mono text-[9px] text-slate-400">Live trades only</div></div></section>
      <section className="rounded-2xl border border-white/[.07] bg-[#0a111f] p-4 shadow-[0_18px_38px_rgba(0,0,0,.2)] sm:p-5"><div className="flex items-center justify-between"><div><p className="font-mono text-[9px] uppercase tracking-[.18em] text-slate-500">Recent activity</p><p className="mt-1 text-sm font-medium text-white">Latest live executions</p></div><Activity className="h-4 w-4 text-blue-300" /></div><div className="mt-4 space-y-2.5">{overview.recent.length ? overview.recent.map(trade => <button type="button" key={trade.id} onClick={() => setLocation(appRoutes.journal)} className="group flex w-full items-center justify-between rounded-lg border border-white/[.055] bg-white/[.018] px-3 py-2.5 text-left hover:border-blue-300/20 hover:bg-blue-500/[.04]"><div><p className="font-mono text-[10px] font-semibold text-slate-200">{trade.symbol} <span className="font-normal text-slate-600">· {trade.direction}</span></p><p className="mt-0.5 text-[10px] text-slate-600">{trade.date}</p></div><span className={`font-mono text-xs ${trade.pnl > 0 ? "text-emerald-300" : trade.pnl < 0 ? "text-rose-300" : "text-slate-400"}`}>{money(trade.pnl)}</span></button>) : <p className="rounded-lg border border-dashed border-white/[.07] px-3 py-8 text-center text-xs text-slate-600">No live trades recorded.</p>}</div><div className="mt-5 grid gap-2 sm:grid-cols-2"><button type="button" onClick={() => setLocation(appRoutes.trades)} className="tf-press rounded-xl border border-blue-400/15 bg-blue-500/[.05] px-3 py-3 text-left text-xs text-blue-200 hover:bg-blue-500/[.1]"><span className="block font-medium">Trade ledger</span><span className="mt-1 block text-[10px] text-slate-500">Log, edit, and export trades.</span></button><button type="button" onClick={() => setLocation(appRoutes.journal)} className="tf-press rounded-xl border border-violet-400/15 bg-violet-500/[.05] px-3 py-3 text-left text-xs text-violet-200 hover:bg-violet-500/[.1]"><span className="block font-medium">Trade Journal</span><span className="mt-1 block text-[10px] text-slate-500">Capture ideas and learning.</span></button></div></section></section>
    <section className="mt-4 grid gap-4 xl:grid-cols-[.9fr_1.1fr]"><section className="rounded-2xl border border-white/[.07] bg-[#0a111f] p-4 sm:p-5"><div className="flex items-center justify-between"><div><p className="font-mono text-[9px] uppercase tracking-[.18em] text-slate-500">Practice & prepare</p><p className="mt-1 text-sm font-medium text-white">Keep simulations separate</p></div><FlaskConical className="h-4 w-4 text-violet-300" /></div><p className="mt-4 text-xs leading-5 text-slate-500">Replay markets in Backtest and review macro risk before an execution. Simulated sessions never affect this Dashboard.</p><div className="mt-4 flex flex-wrap gap-2"><button type="button" onClick={() => setLocation(appRoutes.backtest)} className="tf-press inline-flex items-center gap-1.5 rounded-lg bg-violet-500/[.12] px-3 py-2 text-xs text-violet-200 hover:bg-violet-500/[.18]">Open Backtest <ArrowRight className="h-3.5 w-3.5" /></button><button type="button" onClick={() => setLocation(appRoutes.calendar)} className="tf-press inline-flex items-center gap-1.5 rounded-lg bg-blue-500/[.08] px-3 py-2 text-xs text-blue-200 hover:bg-blue-500/[.14]"><CalendarDays className="h-3.5 w-3.5" />Market Calendar</button></div></section><section className="rounded-2xl border border-white/[.07] bg-[#0a111f] p-4 sm:p-5"><div className="flex items-center justify-between"><div><p className="font-mono text-[9px] uppercase tracking-[.18em] text-slate-500">Quick statistics</p><p className="mt-1 text-sm font-medium text-white">Live trade ledger only</p></div><ShieldCheck className="h-4 w-4 text-emerald-300" /></div><div className="mt-5 grid grid-cols-2 gap-x-5 gap-y-5 sm:grid-cols-4"><div><p className="font-mono text-[8px] uppercase tracking-[.13em] text-slate-600">Profit factor</p><p className="mt-1.5 font-mono text-lg font-semibold text-white">{Number.isFinite(overview.factor) ? overview.factor.toFixed(2) : "∞"}</p></div><div><p className="font-mono text-[8px] uppercase tracking-[.13em] text-slate-600">Avg win</p><p className="mt-1.5 font-mono text-lg font-semibold text-emerald-300">{money(overview.averageWin)}</p></div><div><p className="font-mono text-[8px] uppercase tracking-[.13em] text-slate-600">Avg loss</p><p className="mt-1.5 font-mono text-lg font-semibold text-rose-300">{money(overview.averageLoss)}</p></div><div><p className="font-mono text-[8px] uppercase tracking-[.13em] text-slate-600">Trades</p><p className="mt-1.5 font-mono text-lg font-semibold text-white">{trades.length}</p></div></div><button type="button" onClick={() => setLocation(appRoutes.analytics)} className="tf-press mt-6 inline-flex items-center gap-1.5 text-xs font-medium text-blue-200 hover:text-white">Open setup analytics <ArrowRight className="h-3.5 w-3.5" /></button></section></section>
  </main></div>;
}
