import React from "react";
import { ArrowRight, Bot, BookOpenText, Check, ShieldCheck, WalletCards } from "lucide-react";
import { useLocation } from "wouter";
import { appRoutes } from "@/lib/appRoutes";
import { markWorkspaceEntrySeen, useTradingAccount } from "@/contexts/TradingAccountContext";

export default function WorkspaceEntryChooser({ onComplete }: { onComplete?: () => void }) {
  const [, setLocation] = useLocation();
  const { accounts, selectAccount } = useTradingAccount();
  const continueTo = (path: string) => { markWorkspaceEntrySeen(); onComplete?.(); setLocation(path); };
  const chooseAccount = (id: number) => { selectAccount(id); markWorkspaceEntrySeen(); onComplete?.(); setLocation(appRoutes.dashboard); };

  return <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-[#03060c]/90 px-4 py-8 backdrop-blur-xl" role="dialog" aria-modal="true" aria-labelledby="workspace-entry-title">
    <div className="w-full max-w-3xl rounded-[1.5rem] border border-blue-200/[0.14] bg-[#0a1427] p-5 shadow-[0_30px_100px_rgba(0,0,0,.55)] sm:p-8">
      <div className="mx-auto max-w-xl text-center"><span className="mx-auto grid h-11 w-11 place-items-center rounded-2xl border border-blue-300/[0.20] bg-blue-400/[0.10] text-blue-200"><ShieldCheck className="h-5 w-5" /></span><p className="mt-5 font-mono text-[9px] uppercase tracking-[0.24em] text-blue-200">Private workspace setup</p><h1 id="workspace-entry-title" className="mt-2 text-2xl font-semibold tracking-[-0.04em] text-white sm:text-3xl">Choose how you want to work</h1><p className="mt-3 text-sm leading-6 text-slate-400">Start with a focused account dashboard, connect a broker later, or log a trade without setting up an account first.</p></div>
      <div className="mt-7 grid gap-3 md:grid-cols-3">
        <button type="button" onClick={() => accounts.length ? chooseAccount(accounts[0].id) : continueTo(appRoutes.account)} className="group rounded-2xl border border-blue-300/[0.24] bg-gradient-to-br from-blue-400/[0.16] to-blue-500/[0.04] p-4 text-left transition hover:-translate-y-0.5 hover:border-blue-200/[0.50] hover:bg-blue-400/[0.20] focus:outline-none focus:ring-2 focus:ring-blue-300/60"><span className="grid h-10 w-10 place-items-center rounded-xl bg-blue-400/[0.16] text-blue-200"><WalletCards className="h-5 w-5" /></span><p className="mt-5 text-sm font-semibold text-white">Trading Account</p><p className="mt-2 min-h-10 text-xs leading-5 text-slate-400">{accounts.length ? `Open ${accounts[0].name} dashboard` : "Set up your first private account"}</p><span className="mt-4 inline-flex items-center text-xs font-medium text-blue-200">{accounts.length ? "Open dashboard" : "Create account"}<ArrowRight className="ml-1.5 h-3.5 w-3.5 transition group-hover:translate-x-0.5" /></span></button>
        <button type="button" onClick={() => continueTo(appRoutes.account)} className="group rounded-2xl border border-amber-200/[0.18] bg-amber-300/[0.045] p-4 text-left transition hover:-translate-y-0.5 hover:border-amber-200/[0.36] hover:bg-amber-300/[0.08] focus:outline-none focus:ring-2 focus:ring-amber-200/50"><span className="grid h-10 w-10 place-items-center rounded-xl bg-amber-300/[0.10] text-amber-200"><Bot className="h-5 w-5" /></span><div className="mt-5 flex items-center gap-2"><p className="text-sm font-semibold text-white">Automatic Account Sync</p><span className="rounded-full border border-amber-200/[0.22] px-1.5 py-0.5 font-mono text-[8px] uppercase tracking-wider text-amber-200">Coming soon</span></div><p className="mt-2 min-h-10 text-xs leading-5 text-slate-400">Broker and platform connections are planned for a future release.</p><span className="mt-4 inline-flex items-center text-xs font-medium text-amber-200">View account setup<ArrowRight className="ml-1.5 h-3.5 w-3.5" /></span></button>
        <button type="button" onClick={() => continueTo(appRoutes.trades)} className="group rounded-2xl border border-white/[0.10] bg-white/[0.025] p-4 text-left transition hover:-translate-y-0.5 hover:border-white/[0.24] hover:bg-white/[0.05] focus:outline-none focus:ring-2 focus:ring-blue-300/50"><span className="grid h-10 w-10 place-items-center rounded-xl bg-white/[0.07] text-slate-200"><BookOpenText className="h-5 w-5" /></span><p className="mt-5 text-sm font-semibold text-white">Manual Trade Logging</p><p className="mt-2 min-h-10 text-xs leading-5 text-slate-400">Continue with the existing trade journal flow.</p><span className="mt-4 inline-flex items-center text-xs font-medium text-slate-200">Log a trade<ArrowRight className="ml-1.5 h-3.5 w-3.5" /></span></button>
      </div>
      {accounts.length > 1 && <div className="mt-6 border-t border-white/[0.08] pt-5"><p className="font-mono text-[9px] uppercase tracking-[0.18em] text-slate-600">Your account dashboards</p><div className="mt-3 flex flex-wrap gap-2">{accounts.map(account => <button key={account.id} type="button" onClick={() => chooseAccount(account.id)} className="inline-flex items-center gap-2 rounded-lg border border-white/[0.09] bg-white/[0.025] px-3 py-2 text-xs text-slate-300 hover:border-blue-300/[0.28] hover:text-white"><Check className="h-3 w-3 text-blue-300" />{account.name}</button>)}</div></div>}
    </div>
  </div>;
}
